version: '3.8'

services:
  # Next.js 应用
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AIHUBMIX_API_KEY=${AIHUBMIX_API_KEY}
      - AIHUBMIX_BASE_URL=https://aihubmix.com/v1
      - MONGODB_URI=mongodb://mongodb:27017/ai-chat-bot
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - app-network

  # MongoDB 数据库
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=ai-chat-bot
    networks:
      - app-network

  # MongoDB 管理界面 (可选)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
